version: '3.3'
services:
  postgres:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "55432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    ports:
      - '8181:8080'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin