version: '2.1'
services:
  postgres:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "55432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  keycloak:
    container_name: keycloakproject
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    ports:
      - '8181:8080'
    environment:
      KEYCLOAK_PROFILE_FEATURE_UPLOAD_SCRIPTS: enabled
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - .local/keycloak/:/opt/jboss/keycloak/standalone/data/

  app:
    container_name: app
    image: quarkus/practice-project-jvm
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      depends_on: keycloak
      usernameIonos: ${USERNAME_IONOS}
      passwordIonos: ${PASSWORD_IONOS}
      contractNumberIonos: ${CONTRACT_NUMBER_IONOS}
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/db
      QUARKUS_OIDC_AUTH_SERVER_URL: http://keycloakproject:8080/realms/practice-project
      QUARKUS_OIDC_CREDENTIALS_SECRET: vAUaBjrZcPB4pA6Zq2W0dW1Oi6ALJbuD
      QUARKUS_TRANSACTION_MANAGER_DEFAULT_TRANSACTION_TIMEOUT: 500s
    extra_hosts:
      - "api.ionos.com: 185.48.116.25"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.57.0/24
          gateway: 172.16.57.1