version: '2.1'
services:
  postgres:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "55432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  keycloak:
    container_name: keycloakproject
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    ports:
      - '8181:8080'
    environment:
      DB_VENDOR: h2
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: http://keycloakproject:8080/realms/practice-project

  app:
    container_name: app
    image: quarkus/practice-project-jvm
    ports:
      - '8080:8080'
    environment:
      usernameIonos: ana-maria.iamandii@ionos.com
      passwordIonos: PASSWORD
      contractNumberIonos: 31927984
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/db
      QUARKUS_OIDC_AUTH_SERVER_URL: http://keycloakproject:8080/realms/practice-project