apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  usernameIonos: ${USERNAME_IONOS}
  passwordIonos: ${PASSWORD_IONOS}
  contractNumberIonos: ${CONTRACT_NUMBER_IONOS}
  QUARKUS_OIDC_CREDENTIALS_SECRET: "eA01EjM28jtBlIEGxWPteRwmRWiLDkUc"