apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  usernameIonos: "ana-maria.iamandii@ionos.com"
  passwordIonos: "PASSWORD"
  contractNumberIonos: "31927984"
  QUARKUS_OIDC_CREDENTIALS_SECRET: "IgStCCHF04nsQJ7xHEvzK5j05kSXU2f6"